name: Init NodeJS for Github Actions

on: workflow_call

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: npm

    - name: Install CI script deps
      working-directory: scripts/github-actions
      run: npm ci
